### ISSUE TITLE
Load fixed width data

### ISSUE THREAD

**Issue by adyork** [BCODMO/pipeline-generator#13]
I have a bunch of seabird example files (.btl, .cnv, etc).

Attached are a few examples but I have more if needed.
* Seabird fixed width is 11chars but it would be good to be able to specify length.

[examples_btl_cnv.zip](https://github.com/BCODMO/pipeline-web/files/2958853/examples_btl_cnv.zip)

This is low priority because we need some of the core pipeline steps done more than we need this.  To fully support seabird submissions to BCO-DMO more features will have to be specced out in addition to having fixed width load.  We will probably have to also deal with concatenation of many files, and parsing of seabird headers to extract column names and key info like station, cast, cruise, comments.

**Comment by cschloer** [comment]
You can see this running at `http://bcodmo1-internal.whoi.edu:3000/` by running the pipeline `fixedwidth_test`
