### ISSUE TITLE
Investigate usefulness of existing pipeline extensions

### ISSUE THREAD

**Issue by ashepherd** [BCODMO/pipeline-generator#2]
https://github.com/frictionlessdata?utf8=%E2%9C%93&q=datapackage-pipelines&type=&language=

Is there something in the pattern here, that we should pivot towards?
Installation of custom processors into a Docker container: 
https://github.com/frictionlessdata/datapackage-pipelines/blob/master/Dockerfile#L9

Example: datapackage-pipelines-aws provides `aws.dump.to_s3` 
https://github.com/frictionlessdata/datapackage-pipelines-aws

QUESTION: how do we package our bcodmo_pipeline so that we can also include our custom processors in a Dockerfile, something like:

```
FROM frictionlessdata/datapackage-pipelines:1.7.1

COPY bcodmo_pipeline /bcodmo_pipeline
ENV DPP_PROCESSOR_PATH=/bcodmo_pipeline
```

????

@akariv says, "you can `pip install` [custom processors] in case these are `datapackage-pipelines` extension packages (such as `datapackage-pipelines-aws`). 
If these are processors of your own, you should add them in the container (using Docker's `ADD` or `COPY` commands) and then set the `DPP_PROCESSOR_PATH` environment variable so that they become discoverable by `dpp`"

QUESTION: Do we make `datapackage-pipelines-bcodmo_pipeline` ?
https://github.com/frictionlessdata/datapackage-pipelines#plugins-and-source-descriptors

**Comment by akariv** [comment]
The pattern I've been using mostly is this one: https://github.com/okfn/datapackage_pipelines_od4tj

All processing code is wrapped as a dpp extension, and Dockerfile pip installs it so it becomes available for dpp to use.

**Comment by ashepherd** [comment]
thanks so much @akariv !
